### PR TITLE
First tests and minor refactoring

### PR DESCRIPTION
**Pull request by luissimas**
I think I prefer this PR-based style were we can review and discuss the changes more easily :)

Not much going on here to be honest, added a few unit tests and fixed some inconsistencies on the conversion of formulas to strings. I refactored the function that compares the operators a bit, but It shouldn't impact the functionality at all.

Let me know what you think.

### CODE REVIEW

**Review by ploffredi — DISMISSED** [review]
It is perfectly fine for me using PR-based style (to be honest I'm not used to GitHub PR but I will be up to speed soon)

Regarding the modifications it is great to see you modified exactly what I was thinking to modify in the following hours.
All the modification you made are ok for me especially the unit test needs to be merged immediately IMO so we have a UnitTest starting point.

It would be interesting to explore PropertyBased testing for the parser in the near future.

**Review by ploffredi — COMMENTED** [review]
After a few tests I discovered some difference in the behaviour of the app here an example : 

Yours

yours

Mine 

mine

Something changed the expansion procedure ... maybe it is still correct but needs to be investigated

**Comment by ploffredi** [comment]
Ok the difference is caused by the compare_operators function.

Restored the old clunky function everything is working like before the changes.

I think it will be useful to add some test about it to understand if the different behaviour ends up in a correct result for both the branches.

**Review by ploffredi — COMMENTED** [review]
Adding 

def compare_operators(:atom , _), do: false 

Restores the old behaviour. Why does it effects the result needs to be investigated

  @spec compare_operators(atom(), atom()) :: boolean()
  def compare_operators(op, op), do: false
  def compare_operators(:alpha, _), do: true
  def compare_operators(:atom , _), do: false
  def compare_operators(_, :beta), do: true
  def compare_operators(_, _), do: false

**Comment by ploffredi** [comment]
This is the list of expansions queues in the two different cases for each expansion step : 

Without the "atom" match :

ordered_queue: ["F (p∨(q∧r))→((p∨q)∧(p∨r)) [:2]", "T w [:1]"]
ordered_queue: ["T w [:1]", "F (p∨q)∧(p∨r) [2:4]", "T p∨(q∧r) [2:3]"]
ordered_queue: ["T p∨(q∧r) [2:3]", "F (p∨q)∧(p∨r) [2:4]"]
ordered_queue: ["T q∧r [3:6]", "T p [3:5]", "F (p∨q)∧(p∨r) [2:4]"]
ordered_queue: ["T r [6:8]", "T q [6:7]", "T p [3:5]", "F (p∨q)∧(p∨r) [2:4]"]
ordered_queue: ["T p [3:5]", "T q [6:7]", "F (p∨q)∧(p∨r) [2:4]"]
ordered_queue: ["T q [6:7]", "F (p∨q)∧(p∨r) [2:4]"]
ordered_queue: ["F (p∨q)∧(p∨r) [2:4]"]
ordered_queue: ["F p∨r [4:10]", "F p∨q [4:9]"]
ordered_queue: ["F p∨q [4:9]", "F r [10:12]", "F p [10:11]"]
ordered_queue: ["F q [9:14]", "F p [9:13]", "F p [10:11]", "F r [10:12]"]
ordered_queue: ["F r [10:12]", "F p [10:11]", "F p [9:13]"]
ordered_queue: ["F p [9:13]", "F p [10:11]"]
ordered_queue: ["F p [10:11]"]

With the "atom" match :

ordered_queue: ["F (p∨(q∧r))→((p∨q)∧(p∨r)) [:2]", "T w [:1]"]
ordered_queue: ["F (p∨q)∧(p∨r) [2:4]", "T p∨(q∧r) [2:3]", "T w [:1]"]
ordered_queue: ["F p∨r [4:6]", "F p∨q [4:5]", "T w [:1]", "T p∨(q∧r) [2:3]"] 
ordered_queue: ["F p∨q [4:5]", "F r [6:8]", "F p [6:7]", "T p∨(q∧r) [2:3]", "T w [:1]"]
ordered_queue: ["F q [5:10]", "F p [5:9]", "T w [:1]", "T p∨(q∧r) [2:3]", "F p [6:7]","F r [6:8]"]
ordered_queue: ["F r [6:8]", "F p [6:7]", "T p∨(q∧r) [2:3]", "T w [:1]", "F p [5:9]"]
ordered_queue: ["F p [5:9]", "T w [:1]", "T p∨(q∧r) [2:3]", "F p [6:7]"]
ordered_queue: ["F p [6:7]", "T p∨(q∧r) [2:3]", "T w [:1]"]
ordered_queue: ["T w [:1]", "T p∨(q∧r) [2:3]"]
ordered_queue: ["T p∨(q∧r) [2:3]"]
ordered_queue: ["T q∧r [3:12]", "T p [3:11]"]
ordered_queue: ["T r [12:14]", "T q [12:13]", "T p [3:11]"]
ordered_queue: ["T p [3:11]", "T q [12:13]"]
ordered_queue: ["T q [12:13]"]

It can be deduced that what changes the behaviour is the unnecessary "w" antecedent in the input sequent (I wasn't able to parse sequent like "|-(p∨(q∧r))→((p∨q)∧(p∨r))" before) actually it should be filtered because it is already expanded and the step is not needed

**Comment by luissimas** [comment]
Oh, I really forgot about the `:atom` precedence.

> def compare_operators(:atom , _), do: false
> 
> Restores the old behaviour. Why does it effects the result needs to be investigated

Without the addition of this clause, the `:atom` formulas have precedence over the `:beta` formulas, this caused the order of the queue to change, and therefore the order of the branching rules also changed. I don't think that the resolution was wrong, but it adds unnecessary steps, I think it's important to handle this case.

**Comment by ploffredi** [comment]
Agreed. I will tackle the issue #2 related to the different behaviour afterwards

**Review by ploffredi — APPROVED** [review]
Approved with issue  #2 as follow up

**Pull request merged**
